### ISSUE TITLE
Concerned about destructors

### ISSUE THREAD

**Issue by gretchenfrage** [dtolnay/threadbound#3]
What happens if you have a `ThreadBound<T>`, where `T` implements `Drop`, and the destructor has to run on the same thread it was created on? It seems like you would just drop it on the wrong thread, which could be a potentially invalid operation, which concerns me.

It seems like you would either want to:
- drop the inner element if the `ThreadBound` is dropped on the correct thread, or else log a warning
- upon dropping of the `ThreadBound`, send the inner element through some channel, so that the original thread can receive and drop it

**Comment by dtolnay** [comment]
https://docs.rs/threadbound/0.1/threadbound/struct.ThreadBound.html#impl-Send

```rust
impl<T: Copy> Send for ThreadBound<T>
```

If `T: Copy` then there can't be a `Drop` impl so dropping on a different thread is fine.

If `T` is not `Copy` then `ThreadBound<T>` is not `Send` so it would always be dropped on the original thread.

**Comment by gretchenfrage** [comment]
Aah, I see, that makes sense. Thank you.
