### ISSUE TITLE
src formatting issue on docs.rs

### ISSUE THREAD

**Issue by hcs64** [dtolnay/threadbound#4]
Following any `[src]` link in the docs shows all the line numbers before the code. This was due to https://github.com/rust-lang/docs.rs/issues/264 , which was fixed, but according to https://github.com/rust-lang/rust/issues/57491, affected crates "need to be rebuilt by hand".

**Comment by dtolnay** [comment]
Thanks, I rebuilt the docs in https://docs.rs/threadbound/0.1.1/threadbound/.
